name: Run Karate Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Karate tests
        run: mvn test

      - name: Publish test results
        if: always()
        uses: mikepenz/action-junit-report@v5
        with:
          report_paths: target/surefire-reports/*.xml
          annotate_commit: true

      - name: Upload Karate HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: karate-html-report
          path: target/karate-reports/**
